<div style="align-items: center; justify-content: center; display: flex; height: 100vh;">
    <ul>
        <li><a href="/home">/home</a></li>
        <li><a href="/profile/{user}">/profile/{user}</a></li>
        <li><a href="/fullname/{first_name}/{last_name}">/fullname/{first_name}/{last_name}</a></li>
        <li><a href="/course/{course?}">/course/{course?}</a></li>
        <li><a href="/search/{user}">/search/{user}</a></li>
        <li><a href="/student_list">/student_list</a></li>
    </ul>
</div>

<script>
    // ngl this was generated by gemini ai
    document.querySelectorAll('li a').forEach(a => {
        const template = a.getAttribute('href'); 
        const params = template.match(/\{.*?\}/g) || [];
        
        params.forEach(param => {
            const input = document.createElement('input');
            input.type = 'text';
            input.placeholder = param;
            input.style.marginLeft = '8px';
            
            input.addEventListener('input', () => {
                let updatedUrl = template;
                
                a.parentElement.querySelectorAll('input').forEach(inp => {
                    const isOptional = inp.placeholder.includes('?');
                    const fallback = isOptional ? '' : inp.placeholder;
                    const value = inp.value.trim() || fallback; 
                    
                    updatedUrl = updatedUrl.replace(inp.placeholder, value);
                });
                
                a.href = updatedUrl;
                a.textContent = updatedUrl;
            });
            
            a.parentElement.appendChild(input);
        });

        const firstInput = a.parentElement.querySelector('input');
        if (firstInput) {
            firstInput.dispatchEvent(new Event('input'));
        }
    });
</script>